export interface UserProfile {
  uid: string;
  email: string;
  name?: string;
  role: 'customer' | 'admin';
}

export interface Medicine {
  id: string;
  name: string;
  description: string;
  price: number;
  stock: number;
  imageUrl: string;
  category: string;
  requiresPrescription?: boolean;
}

export interface CartItem {
  id?: string;
  medicineId: string;
  name: string;
  price: number;
  imageUrl: string;
  quantity: number;
}

export interface Order {
  id?: string;
  userId: string;
  items: CartItem[];
  total: number;
  status: 'Pending' | 'Paid' | 'Processing' | 'Dispatched' | 'Out for Delivery' | 'Delivered' | 'Cancelled';
  deliveryOption?: 'Standard' | 'Express';
  shippingAddress: any;
  createdAt: any;
  paymentMethod?: 'MPESA' | 'Cash on Delivery';
  customerName?: string;
  customerPhone?: string;
}

export interface Prescription {
  id: string;
  userId: string;
  patientName: string;
  phoneNumber?: string;
  email?: string;
  prescriptionImageUrl: string;
  status: 'pending' | 'approved' | 'rejected';
  uploadedAt: any;
  notes?: string;
  reviewedBy?: string;
  reviewNotes?: string;
  reviewedAt?: any;
}

export interface FollowUp {
    id?: string;
    patientId: string;
    patientName: string;
    email: string;
    phoneNumber?: string;
    message: string;
    sentBy: string;
    sentAt: any;
    autoGenerated: boolean;
}
