'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { useToast } from '@/hooks/use-toast';
import { Loader2, Send, Sparkles } from 'lucide-react';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { sendFollowUpMessage } from '@/lib/firestore';
import { db } from '@/lib/firebase';
import { useAuth } from '@/hooks/use-auth';

// This would be fetched from Firestore in a real app
const mockPatients = [
  { uid: "USR001", email: "john.doe@email.com", name: "John Doe", phoneNumber: "0712345678" },
  { uid: "USR002", email: "jane.smith@email.com", name: "Jane Smith", phoneNumber: "0787654321" },
  { uid: "USR003", email: "sam.wilson@email.com", name: "Sam Wilson", phoneNumber: "0711223344" },
];

async function generateAutoMessage(patientName: string, context: string) {
    // In a real app, this would call a Genkit flow
    await new Promise(resolve => setTimeout(resolve, 500));
    return `Hello ${patientName}, this is a friendly follow-up from MediTrack Pro regarding your recent ${context}. We hope you're feeling better. Please let us know if you have any questions.`;
}

export default function FollowUpPage() {
  const [message, setMessage] = useState('');
  const [isSending, setIsSending] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [selectedPatientId, setSelectedPatientId] = useState<string | null>(null);
  const { toast } = useToast();
  const { user } = useAuth();
  
  const selectedPatient = mockPatients.find(p => p.uid === selectedPatientId);

  const handleSend = async () => {
    if (!message || !selectedPatient || !user) {
        toast({
            title: "Error",
            description: "Please select a patient and write a message.",
            variant: "destructive"
        });
        return;
    }
    setIsSending(true);
    try {
        await sendFollowUpMessage(db, {
            patientId: selectedPatient.uid,
            patientName: selectedPatient.name,
            email: selectedPatient.email,
            phoneNumber: selectedPatient.phoneNumber,
            message,
            sentBy: user.uid,
            autoGenerated: false,
        });
        setMessage('');
        toast({
            title: "✅ Message Sent",
            description: `Follow-up sent to ${selectedPatient.name}`,
        });
    } catch (error) {
         toast({
            title: "❌ Failed to send message",
            description: "An error occurred. Please try again.",
            variant: "destructive"
        });
    } finally {
        setIsSending(false);
    }
  };

  const handleAutoGenerate = async () => {
    if (!selectedPatient) {
         toast({
            title: "Error",
            description: "Please select a patient first.",
            variant: "destructive"
        });
        return;
    }
    setIsGenerating(true);
    const autoMessage = await generateAutoMessage(selectedPatient.name, "prescription");
    setMessage(autoMessage);
    setIsGenerating(false);
  };

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-3xl font-bold font-headline">Patient Follow-Up</h1>
      </div>
      <Card className="max-w-3xl">
        <CardHeader>
            <CardTitle>Send a Message</CardTitle>
            <CardDescription>
                Contact patients with reminders, check-ins, or feedback requests.
            </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
            <div>
                 <Select onValueChange={setSelectedPatientId}>
                    <SelectTrigger>
                        <SelectValue placeholder="Select a patient..." />
                    </SelectTrigger>
                    <SelectContent>
                        {mockPatients.map(p => (
                            <SelectItem key={p.uid} value={p.uid}>
                                {p.name} - {p.email}
                            </SelectItem>
                        ))}
                    </SelectContent>
                </Select>
            </div>
            <Textarea
                value={message}
                onChange={(e) => setMessage(e.target.value)}
                placeholder="Write your follow-up message here..."
                rows={6}
                disabled={!selectedPatient}
            />
            <div className="flex flex-col sm:flex-row gap-2">
                <Button onClick={handleAutoGenerate} disabled={isGenerating || !selectedPatient}>
                    {isGenerating ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Sparkles className="mr-2 h-4 w-4" />}
                    Generate with AI
                </Button>
                <Button onClick={handleSend} disabled={isSending || !message || !selectedPatient}>
                    {isSending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Send className="mr-2 h-4 w-4" />}
                    Send Message
                </Button>
            </div>
        </CardContent>
      </Card>
    </div>
  );
}
